name: torchmd-net
channels:
  - pytorch
  - rusty1s
  - conda-forge
dependencies:
  - matplotlib
  - pip
  - pytorch==1.8.0
  - pytorch-geometric=1.7.2=py36_torch_1.8.0_cpu
  - pytorch-lightning==1.3.1
  - ase
  - h5py
  - tqdm
  - scipy
