[build-system]
requires = ["setuptools", "wheel", "ninja"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ['py38', 'py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  
)/
'''