seed_everything: 19384
trainer:
  resume_from_checkpoint: null
  profiler: null
  accelerator: 'ddp'
  benchmark: false
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: '/local_scratch/musil/chign/test_4/'
        name: tensorboard
        version: ''
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: '/local_scratch/musil/chign/test_4/'
        name: ''
        version: ''
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'validation_loss'
        patience: 10
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: '/local_scratch/musil/chign/test_4/'
        monitor: 'validation_loss'
        save_top_k: 5
        every_n_epochs: 2
        filename: '{epoch}-{validation_loss:.4f}-{test_loss:.4f}'
  default_root_dir: '/local_scratch/musil/chign/test_4/'
  log_every_n_steps: 10
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 4
  log_gpu_memory: null
  track_grad_norm: inf
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  max_time: null
  plugins:
    - class_path: pytorch_lightning.plugins.DDPPlugin
  precision: 32
  weights_summary: top
  deterministic: true
  auto_lr_find: false
  terminate_on_nan: true
  amp_backend: native
  amp_level: O2
model:
  calculator:
    class_path: torchmdnet2.nn.spherical_equivariants.PowerSpectrum
    init_args:
      max_radial: 10
      max_angular: 3
      interaction_cutoff: 15
      gaussian_sigma_constant: 1.5
      normalize: true
      smooth_width: 0.5
      species:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
  hidden_widths:
    - 500
    - 200
    - 100
  weights_per_species: false
  activation_func:
    class_path: torch.nn.Tanh
  property: 'energy'
  derivative: 'forces'
  factors:
    forces: 1.
  lr: 0.001
  weight_decay: 0
  lr_factor: 0.9999
  lr_patience: 100
  lr_min: 1.0e-07
  lr_warmup_steps: 0
  test_interval: 1
data:
  dataset:
    class_path: torchmdnet2.dataset.ChignolinDataset
    init_args:
      root: '/local_scratch/musil/datasets/chignolin/'
  log_dir: '/local_scratch/musil/chign/test_4/'
  val_ratio: 0.01
  test_ratio: 0.01
  batch_size: 200
  inference_batch_size: 200
  num_workers: 16
  train_stride: 100
