seed_everything: 19384
trainer:
  resume_from_checkpoint: null
  profiler: null
  accelerator: 'ddp'
  benchmark: false
  logger:
    - class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
        save_dir: '/local_scratch/musil/chign/schnet/test_0/'
        name: tensorboard
        version: ''
    - class_path: pytorch_lightning.loggers.CSVLogger
      init_args:
        save_dir: '/local_scratch/musil/chign/schnet/test_0/'
        name: ''
        version: ''
  checkpoint_callback: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'validation_loss'
        patience: 10
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        dirpath: '/local_scratch/musil/chign/schnet/test_0/'
        monitor: 'validation_loss'
        save_top_k: 5
        every_n_epochs: 2
        filename: '{epoch}-{validation_loss:.4f}-{test_loss:.4f}'
  default_root_dir: '/local_scratch/musil/chign/schnet/test_0/'
  log_every_n_steps: 10
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 4
  log_gpu_memory: null
  track_grad_norm: inf
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 50
  max_time: null
  plugins:
    - class_path: pytorch_lightning.plugins.DDPPlugin
  precision: 32
  weights_summary: top
  deterministic: true
  auto_lr_find: false
  terminate_on_nan: true
  amp_backend: native
  amp_level: O2
model:
  embedding_size: 128
  hidden_channels: 128
  num_filters: 128
  num_interactions: 3
  num_rbf: 50
  rbf_type: expnorm
  trainable_rbf: false
  activation: tanh
  neighbor_embedding: true
  cutoff_lower: 0.0
  cutoff_upper: 30.0
  n_layers: 3
  reduction_factor: 1
  cfconv_aggr: mean
  target_name: forces
  derivative: true
  lr: 0.0001
  weight_decay: 0
  lr_factor: 0.9999
  lr_patience: 100
  lr_min: 1.0e-07
  lr_warmup_steps: 0
  test_interval: 1
data:
  dataset_name: chignolin
  dataset_root: '/local_scratch/musil/datasets/chignolin/'
  log_dir: '/local_scratch/musil/chign/schnet/test_0/'
  val_ratio: 0.05
  test_ratio: 0.05
  batch_size: 1024
  inference_batch_size: 1024
  num_workers: 6
  train_stride: 100
