load_model: null
conf: null
num_epochs: 3000
batch_size: 4
inference_batch_size: 64
lr: 0.001
lr_patience: 30
lr_min: 1.0e-07
lr_factor: 0.8
lr_warmup_steps: 1000
early_stopping_patience: 300
weight_decay: 0.0
ema_alpha_y: 0.05
ema_alpha_dy: 1.0
ngpus: -1
num_nodes: 1
precision: 32
log_dir: /shared/philipp/geometric/md17/logs/transformer-aspirin-0
splits: null
train_size: 950
val_size: 50
test_size: null
test_interval: 10
save_interval: 10
seed: 10
distributed_backend: ddp
num_workers: 4
redirect: true
dataset: MD17
dataset_root: ~/data
dataset_arg: aspirin
coord_files: null
embed_files: null
energy_files: null
force_files: null
energy_weight: 0.2
force_weight: 0.8
model: transformer
prior_model: null
embedding_dimension: 256
num_layers: 6
num_rbf: 32
activation: silu
rbf_type: expnorm
trainable_rbf: true
neighbor_embedding: true
distance_influence: both
attn_activation: silu
num_heads: 8
derivative: true
cutoff_lower: 0.0
cutoff_upper: 9.0
atom_filter: -1
max_z: 100
max_num_neighbors: 32
standardize: true
reduce_op: add
dipole: false
num_filters: 256
